steps:
  build:
    image: python:3.9-slim
    commands:
      - apt-get update && apt-get install -y build-essential
      - pip install -r requirements.txt
      - python -c "import dash_app.index; print('Import successful')"
    when:
      - event: [push, pull_request]

  deploy:
    image: docker/compose:1.29.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/woodpecker/src/github.com/colsen-bu/doser-responser
    working_dir: /woodpecker/src/github.com/colsen-bu/doser-responser
    commands:
      - pwd
      - ls -la
      - cat docker-compose.yml
      - ls -la sample_data.csv
      - docker-compose down || echo "No running containers"
      - docker-compose up -d --build
      - docker image prune -f
    when:
      - event: push
      - branch: main


  notify:
    image: alpine:latest
    commands:
      - echo "✅ Doser Responser deployed successfully!"
    when:
      - event: push
      - branch: main
      - status: [success]
