steps:
  # Build and test the application
  build:
    image: python:3.9-slim
    commands:
      - apt-get update && apt-get install -y build-essential
      - pip install -r requirements.txt
      - cd dash_app && python -c "import index; print('Import successful')"
    when:
      - event: [push, pull_request]

  # Build and deploy Docker image locally
  deploy:
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      # Build the Docker image locally using the current workspace
      - docker build -t doser-responser:latest .
      # Stop and remove existing container if it exists
      - docker stop doser-responser || true
      - docker rm doser-responser || true
      # Run the new container
      - docker run -d --name doser-responser --restart unless-stopped -p 7090:7090 doser-responser:latest
      # Clean up old images to save space
      - docker image prune -f
    when:
      - event: push
      - branch: main

  # Notify deployment status
  notify:
    image: alpine:latest
    commands:
      - echo "Doser Responser deployed successfully!"
      - echo "Deployment completed"
    when:
      - event: push
      - branch: main
      - status: [success]
