steps:
  # Build and test the application
  build:
    image: python:3.9-slim
    commands:
      - apt-get update && apt-get install -y build-essential
      - pip install -r requirements.txt
      - python -c "import dash_app.index; print('Import successful')"
    when:
      - event: [push, pull_request]

  # Build and deploy with docker-compose
  deploy:
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      # Install docker-compose
      - apk add --no-cache curl py3-pip python3
      - pip3 install docker-compose
      # Stop and remove existing containers
      - docker-compose down || true
      # Build and start with docker-compose
      - docker-compose build --no-cache
      - docker-compose up -d
      # Clean up old images to save space
      - docker image prune -f
    when:
      - event: push
      - branch: main

  # Notify deployment status
  notify:
    image: alpine:latest
    commands:
      - echo "Doser Responser deployed successfully!"
      - echo "Deployment completed"
    when:
      - event: push
      - branch: main
      - status: [success]
