steps:
  # Step 1: Build and test the application
  build:
    image: python:3.9-slim
    commands:
      - apt-get update && apt-get install -y build-essential
      - pip install -r requirements.txt
      - python -c "import dash_app.index; print('Import successful')"
    when:
      event: [push, pull_request]

  # Step 2: Build and deploy using Docker Compose
  deploy:
    image: docker/compose:1.29.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose down || true
      - docker-compose build --no-cache
      - docker-compose up -d
      - docker image prune -f
    when:
      event: push
      branch: main

  # Step 3: Notify success
  notify:
    image: alpine:latest
    commands:
      - echo "✅ Doser Responser deployed successfully!"
      - echo "🔔 Deployment completed"
    when:
      event: push
      branch: main
      status: [success]
