networks:
  doser-network:
    driver: bridge
    name: doser-network
  npm-shared:
    external: true  # this refers to the one you created manually

services:
  doser-responser:
    build: .
    container_name: doser-responser
    environment:
      - FLASK_ENV=production
    volumes:
      - ./sample_data.csv:/app/sample_data.csv
    restart: unless-stopped
    networks:
      - doser-network
      - npm-shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7090/_dash-layout"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s